;; -*- lexical-binding: t -*-

;;;  Startup timing
(defun my-display-startup-time ()
  "Report how long Emacs took to start (and GC count)."
  (message "Emacs loaded in %s with %d garbage collections."
           (format "%.2f seconds"
                   (float-time (time-subtract after-init-time before-init-time)))
           gcs-done))
(add-hook 'emacs-startup-hook #'my-display-startup-time)

;;;  Symlink safety – follow without prompting
(setq vc-follow-symlinks t)

;;;  Org-mode literate config bootstrap
(require 'org)        ;; core Org
(require 'ob-tangle)  ;; Org-Babel tangle support

(defvar my-config-org (expand-file-name "config.org" user-emacs-directory)
  "Absolute path to the literate configuration file.")

(defvar my-config-el  (expand-file-name "config.el"  user-emacs-directory)
  "Destination of the tangled Emacs-Lisp code.")

(defun my-tangle-config ()
  "When saving `config.org`, tangle it and reload the result."
  (when (string= (file-truename (buffer-file-name))
                 (file-truename my-config-org))
    (message "Tangling %s …" my-config-org)
    (org-babel-tangle-file my-config-org)
    (load-file my-config-el)
    (message "Reloaded config.el")))

(add-hook 'after-save-hook #'my-tangle-config)

;; One-time tangle on startup if config.el is missing or stale
(when (or (not (file-exists-p my-config-el))
          (file-newer-than-file-p my-config-org my-config-el))
  (message "Generating %s from %s …" my-config-el my-config-org)
  (org-babel-tangle-file my-config-org))

;; Load the real configuration
(when (file-exists-p my-config-el)
  (load-file my-config-el))


;;;  Custom – generated by M-x customize
(custom-set-variables
 ;; If you edit this section by hand, be careful!
 '(package-selected-packages
   '(counsel-projectile list-packages-ext go-projectile exec-path-from-shell
     magit helpful xenops company-reftex yasnippet cdlatex auctex company-math
     pyvenv blacken flycheck-pycheckers company-jedi flycheck pdf-view pdf-tools
     vertico undo-tree tablist orderless flyspell-correct expand-region
     doom-themes doom-modeline consult company all-the-icons)))
(custom-set-faces
 ;; Customize faces here (left empty intentionally).
 )
